version: "3.8"

services:
  service_1:
    build: ./service_1
    container_name: service_1
    expose:
      - "8001"

  service_2:
    build: ./service_2
    container_name: service_2
    expose:
      - "8002"

  nginx:
    build: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "8080:8080"
    depends_on:
      - service_1
      - service_2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # attaching the conf volume as mount so that it can be changed dynamically 
